export const HARDCODED_LOCALIDADES: Record<string, string[]> = {
  "Mendoza": [
    "Agrelo", "Agua Escondida", "Alto del Olvido", "Alto Salvador", "Alto Verde", "Andrade",
    "Bardas Blancas", "Barrancas", "Barrio ADINA", "Barrio Belgrano Norte", "Barrio Chivilcoy",
    "Barrio Cooperativa Los Campamentos", "Barrio Echevarrieta", "Barrio El Nevado", "Barrio Empleados de Comercio",
    "Barrio Intendencia", "Barrio Jesús de Nazaret", "Barrio Jocolí II", "Barrio La Esperanza", "Barrio Las Rosas",
    "Barrio Los Jarilleros", "Barrio María Auxiliadora", "Barrio Perdriel IV", "Barrio Primavera", "Barrio Rivadavia",
    "Barrio San Cayetano", "Barrio Tres Olivos", "Blanco Encalada", "Bowen",
    "Cacheuta", "Campo de los Andes", "Capdevila", "Capitán Montoya", "Carmensa", "Chacras de Coria", "Chapanay",
    "Chilecito", "Chivilcoy", "Colonia Las Rosas", "Cordón del Plata", "La Costa", "Costa de Araujo", "Costa El Toledano",
    "Costa Flores", "Cruz de Piedra", "Cuadro Benegas", "Cuadro Nacional", "Cuadro Ortega",
    "Desaguadero", "Doce de Octubre",
    "El Carmelo", "El Carrizal", "El Central", "El Cepillo", "El Challao", "El Manzano Histórico", "El Marcado",
    "El Mirador", "El Nihuil", "El Paramillo", "El Pedregal", "El Peral", "El Plumerillo", "El Retamo", "El Salto",
    "El Sosneado", "El Tropezón", "El Vergel", "Eugenio Bustos",
    "General Alvear", "Goudge",
    "Ingeniero Giagnoni", "Ingeniero Gustavo André",
    "Jaime Prats", "Jocolí", "Jocolí Viejo", "Junín",
    "La Arboleda", "La Central", "La Cieneguita", "La Colonia", "La Consulta", "La Dormida", "La Esperanza",
    "La Florida", "La Libertad", "La Llave", "La Palmera", "La Paz", "La Pega", "La Reducción", "Lagunas de Bartoluzzi",
    "Las Carditas", "Las Catitas", "Las Compuertas", "Las Cuevas", "Las Leñas", "Las Malvinas", "Las Paredes",
    "Las Vegas", "Las Violetas", "Los Árboles", "Los Barriales", "Los Campamentos", "Los Charabones", "Los Compartos",
    "Los Penitentes", "Los Reyunos", "Los Sauces",
    "Malargüe", "Manantiales", "Medrano", "Monte Comán", "Montecaseros", "Mundo Nuevo",
    "Nueva California",
    "Palmira", "Papagayos", "Pareditas", "Perdriel", "Philipps", "Piedras Blancas", "Pobre Diablo", "Polvaredas",
    "Potrerillos", "Puente del Inca", "Punta de Vacas", "Punta del Agua",
    "Rama Caída", "Real del Padre", "Rivadavia", "Rodeo del Medio", "Rodríguez Peña", "Russell",
    "Salto de las Rosas", "San Isidro", "San José", "San Martín", "San Roque", "Santa María de Oro", "Santa Rosa",
    "Tres de Mayo", "Tres Esquinas", "Tres Porteñas", "Tunuyán", "Tupungato",
    "Ugarteche", "Uspallata",
    "Valle del Sol", "Vallecitos", "Villa Antigua", "Villa Atuel", "Villa Atuel Norte", "Villa Bastías", "Villa El Refugio",
    "Villa San Carlos", "Villa Teresa", "Villa Tulumaya", "Villa Veinticinco de Mayo", "Vista Flores", "Vistalba"
  ],
  "San Juan": [
    "Albardón", "Angaco", "Calingasta", "Capital", "Caucete", "Chimbas", "Iglesia", "Jáchal",
    "Nueve de Julio (9 de Julio)", "Pocito", "Rawson", "Rivadavia", "San Martín", "Santa Lucía", "Sarmiento",
    "Ullum", "Valle Fértil", "Veinticinco de Mayo (25 de Mayo)", "Zonda"
  ],
  "San Luis": [
    "Algarrobo Grande", "Alsa", "Alto Lindo", "Alto Pelado", "Alto Pencoso", "Anchorena", "Árbol Solo", "Arizona",
    "Bagual", "Bajos Hondos", "Bajada Nueva", "Balcarce", "Balde", "Balde de Escudero", "Balde de Escurria",
    "Balde de las Torres", "Balde de Puertas", "Balde Viejo", "Barranca Colorada", "Batavia", "Beazley", "Bella Vista",
    "Buena Esperanza", "Buena Vista",
    "Cabeza de Novillo", "Caldenadas", "Candelaria", "Canteras", "Cañada Honda", "Carpintería", "Cazador", "Cerro de Oro",
    "Chalanta", "Chimborazo", "Chipiscú", "Chischaquita", "Chosmes", "Cochequingán", "Colonia Calzada", "Colonia Santa Virginia",
    "Colonia Urdániz", "Comandante Granville", "Concarán", "Conlara", "Coronel Alzogaray", "Coronel Segovia", "Cortaderas",
    "Crámer", "Cruz de Caña",
    "Daniel Dónovan", "Donado",
    "El Águila", "El Baldecito", "El Cadillo", "El Carmen", "El Chañar", "El Chorrillo", "El Hormiguero", "El Manantial Escondido",
    "El Martillo", "El Milagro", "El Mollar", "El Pantanillo", "El Pastal", "El Portezuelo", "El Porvenir", "El Puesto",
    "El Recuerdo", "El Retamo", "El Rodeo", "El Sauce", "El Tala", "El Volcán", "Eleodoro Lobos", "Estancia Grande",
    "Fortín El Patria", "Fortuna", "Fraga", "Frisia",
    "Gorgonta", "Guanaco Pampa",
    "Huejeda",
    "Jarilla", "Juan Jorba", "Juan Llerena", "Juan W. Gez", "Juana Koslay", "Justo Daract",
    "La Angelina", "La Bajada", "La Botija", "La Brea", "La Calera", "La Carolina", "La Cocha", "La Costa", "La Esquina",
    "La Estrella", "La Florida", "La Irene", "La Majada", "La Maroma", "La Melina", "La Nélida", "La Pampa Grande",
    "La Puerta", "La Punilla", "La Punta", "La Sala", "La Seña", "La Toma", "La Totora", "La Tranca", "La Verde", "La Vertiente",
    "Las Aguadas", "Las Barrancas", "Las Cañadas", "Las Chacras", "Las Chimbas", "Las Gamas", "Las Isletas", "Las Lagunas",
    "Las Palomas", "Las Totoras", "Las Vertientes", "Lafinur", "Lagunas Largas", "Lavaisse", "Leandro N. Alem",
    "Libertador General San Martín", "Liborio Luna", "Loma Blanca", "Lomas Blancas", "Los Alanices", "Los Arguelos",
    "Los Cajones", "Los Cerrillos", "Los Chañares", "Los Chilcas", "Los Coros", "Los Duraznitos", "Los Lobos", "Los Molles",
    "Los Ranchos", "Luján",
    "Manantial Blanco", "Manantiales", "Martín de Loyola", "Merlo", "Molino Chico", "Mosmota",
    "Nahuel Mapá", "Naschel", "Navia", "Nogolí", "Nueva Constitución", "Nueva Escocia", "Nueva Galia",
    "Ojo de Agua", "Ojos del Río",
    "Pantanillo", "Papagayos", "Paso Grande", "Paso del Rey", "Pedernera", "Pescadores", "Piedras Chatas", "Polledo",
    "Potrerillo", "Potrero de los Funes", "Pozo del Carril", "Pozo del Tala", "Punta del Agua",
    "Quines",
    "Ranquelcó", "Renca", "Rincón del Carmen", "Riocito", "Río Grande", "Río Juan Gómez", "Río Quinto", "Rosario",
    "Saladillo", "Salado", "Salinas del Bebedero", "San Ambrosio", "San Antonio", "San Eduardo", "San Felipe",
    "San Francisco del Monte de Oro", "San Gerónimo", "San Ignacio", "San Isidro", "San José del Morro", "San Luis",
    "San Martín", "San Martín del Alto Negro", "San Miguel", "San Pablo", "San Pedro", "San Roque", "San Salvador",
    "Santa Rosa", "Santa Rosa del Conlara", "Santo Tómas", "Socoscora", "Soven", "Suyuque Nuevo", "Suyuque Viejo",
    "Tala Verde", "Talita", "Talleres", "Tilisarao", "Toro Negro", "Toscal", "Trapiche", "Travesía", "Tres Amigos",
    "Unión", "Usiyal",
    "Vaca Parada", "Valle de Pancanta", "Varela", "Villa de la Quebrada", "Villa de Praga", "Villa del Carmen",
    "Villa General Roca", "Villa Larca", "Villa Mercedes", "Villa Reynolds", "Villa Salles",
    "Zanjitas"
  ]
};
